SET search_path TO app, public;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS google_calendar_sync_jobs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'success', 'failed')),
  started_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  started_at TIMESTAMPTZ DEFAULT now(),
  finished_at TIMESTAMPTZ,
  fetched INTEGER NOT NULL DEFAULT 0,
  imported INTEGER NOT NULL DEFAULT 0,
  updated INTEGER NOT NULL DEFAULT 0,
  cancelled INTEGER NOT NULL DEFAULT 0,
  unchanged INTEGER NOT NULL DEFAULT 0,
  imported_with_warning INTEGER NOT NULL DEFAULT 0,
  all_day_events INTEGER NOT NULL DEFAULT 0,
  conflicts INTEGER NOT NULL DEFAULT 0,
  invalid_time INTEGER NOT NULL DEFAULT 0,
  partial BOOLEAN NOT NULL DEFAULT false,
  error_message TEXT,
  request_json TEXT,
  cursor_json TEXT,
  progress_json TEXT,
  last_heartbeat_at TIMESTAMPTZ,
  result_json TEXT
);

CREATE TABLE IF NOT EXISTS app_notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  metadata TEXT,
  created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_patients_name_normalized ON patients(lower(btrim(first_name)), lower(btrim(last_name)));
CREATE INDEX IF NOT EXISTS idx_patients_email_normalized ON patients(lower(btrim(COALESCE(email, ''))));
CREATE INDEX IF NOT EXISTS idx_patients_phone_digits ON patients(regexp_replace(COALESCE(phone, ''), '\D', '', 'g'));
CREATE INDEX IF NOT EXISTS idx_google_calendar_sync_jobs_status ON google_calendar_sync_jobs(status, started_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_google_calendar_sync_jobs_one_running ON google_calendar_sync_jobs(status) WHERE status = 'running';
CREATE INDEX IF NOT EXISTS idx_app_notifications_created ON app_notifications(created_at DESC);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM appointments WHERE google_event_id IS NOT NULL GROUP BY google_event_id HAVING COUNT(*) > 1
  ) THEN
    RAISE EXCEPTION 'Duplicate google_event_id rows exist. Repair them before applying this migration.';
  END IF;
  CREATE UNIQUE INDEX IF NOT EXISTS idx_appointments_google_event_id ON appointments(google_event_id) WHERE google_event_id IS NOT NULL;
END $$;

-- These fields were historically added by runtime schema initialization.
-- They must exist before the calendar repository and overlap checks run.
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS google_event_type TEXT NOT NULL DEFAULT 'appointment';
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS google_title TEXT;
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS google_patient_match_status TEXT;
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS google_patient_match_note TEXT;
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS patient_match_locked BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS google_sync_warning TEXT;
ALTER TABLE appointments
  ADD COLUMN IF NOT EXISTS google_sync_warning_code TEXT;

-- Defense in depth: referenced visits/invoices must belong to the same patient.
CREATE UNIQUE INDEX IF NOT EXISTS idx_visit_records_id_patient ON visit_records(id, patient_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_id_patient ON invoices(id, patient_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'patient_documents_visit_patient_fkey') THEN
    ALTER TABLE patient_documents
      ADD CONSTRAINT patient_documents_visit_patient_fkey
      FOREIGN KEY (visit_record_id, patient_id) REFERENCES visit_records(id, patient_id) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'invoices_visit_patient_fkey') THEN
    ALTER TABLE invoices
      ADD CONSTRAINT invoices_visit_patient_fkey
      FOREIGN KEY (visit_record_id, patient_id) REFERENCES visit_records(id, patient_id) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'insurance_claims_visit_patient_fkey') THEN
    ALTER TABLE insurance_claims
      ADD CONSTRAINT insurance_claims_visit_patient_fkey
      FOREIGN KEY (visit_record_id, patient_id) REFERENCES visit_records(id, patient_id) NOT VALID;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'insurance_claims_invoice_patient_fkey') THEN
    ALTER TABLE insurance_claims
      ADD CONSTRAINT insurance_claims_invoice_patient_fkey
      FOREIGN KEY (invoice_id, patient_id) REFERENCES invoices(id, patient_id) NOT VALID;
  END IF;
END $$;

ALTER TABLE patient_documents VALIDATE CONSTRAINT patient_documents_visit_patient_fkey;
ALTER TABLE invoices VALIDATE CONSTRAINT invoices_visit_patient_fkey;
ALTER TABLE insurance_claims VALIDATE CONSTRAINT insurance_claims_visit_patient_fkey;
ALTER TABLE insurance_claims VALIDATE CONSTRAINT insurance_claims_invoice_patient_fkey;

-- Private bucket; plain PostgreSQL CI does not include Supabase's storage schema.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'storage') THEN
    INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    VALUES (
      'patient-documents',
      'patient-documents',
      false,
      10485760,
      ARRAY['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'application/dicom', 'application/octet-stream']
    )
    ON CONFLICT (id) DO UPDATE
    SET public = false,
        file_size_limit = EXCLUDED.file_size_limit,
        allowed_mime_types = EXCLUDED.allowed_mime_types;
  END IF;
END $$;
