SET search_path TO app, public;

-- Additive migration. Legacy refresh_tokens are deliberately not promoted:
-- users reauthenticate once when the session-aware application is deployed.
CREATE TABLE IF NOT EXISTS auth_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  previous_token_hash TEXT,
  previous_valid_until TIMESTAMPTZ,
  generation INTEGER NOT NULL DEFAULT 0,
  user_agent TEXT,
  ip_address TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  last_activity_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CHECK (expires_at > created_at)
);
CREATE INDEX IF NOT EXISTS auth_sessions_previous_token_idx ON auth_sessions(previous_token_hash)
  WHERE previous_token_hash IS NOT NULL;
CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions(user_id);
ALTER TABLE auth_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON auth_sessions FROM PUBLIC;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON auth_sessions FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON auth_sessions FROM authenticated;
  END IF;
END $$;
